### ISSUE TITLE
Suggestion: Option to turn off the chat message

### ISSUE THREAD

**Issue by BLUEChester** [gbl/StepUp#11]
Hey, just find it annoying that there's a message saying that the mod is enabled every time I join my game, I'm aware that it's enabled as I have put it in my mod folder lol.

Awesome mod though, thanks for your work on it!

**Comment by gbl** [comment]
.. until you join a server that will kick ,or worse ban, you for cheating when you step up.  That's a reminder which state the mod is in last time you left, which can be quite important in some cases.
