### ISSUE TITLE
ETA of 1.20 ver? Or just change the version in fabric.mod.json?

### ISSUE THREAD

**Issue by Mudxiej** [gbl/StepUp#12]
You know what im here for, so hands up, and answer CAREFULLY :DD

**Comment by Zorklis** [comment]
@Soulfate24 I hope you update StepUpLite, it works well too

**Comment by Mudxiej** [comment]
> @Soulfate24 I hope you update StepUpLite, it works well too

I didn't know this mod was abandoned. Ty for letting me know that <3

**Comment by Zorklis** [comment]
I have no idea if it's abandoned, there's always a chance gbl comes back

**Comment by Soulfate24** [comment]
I've tested StepUpLite on 1.20.1 (with Quilt, btw) and it's working, so no need to update it unless there are crashes (I've just tested ingame steps and J key to switch between modes)

**Comment by Zorklis** [comment]
@Mudxiej Reopen until GBL updates it
