### ISSUE TITLE
Please update for 1.20

### ISSUE THREAD

**Issue by Dabbpool** [gbl/StepUp#13]
i reverted to 19.2 to use this because i got really dependent on this and now i have to update for my server to 1.20 and the game is pretty much unplayable without this mod and i feel the same way about the clickthrough mod

**Comment by Dabbpool** [comment]
ty so much for updating this

**Comment by Zorklis** [comment]
Can confirm 1.20-fabric0.83.0-1.1 seems to work fine on 1.20.1
