### ISSUE TITLE
[BUG] Not able to open the config via ModMenu

### ISSUE THREAD

**Issue by itsMarkiS** [gbl/StepUp#15]
the game crashes, thats it

**Comment by gbl** [comment]
I need the full logs, or I can't do anything but say "it works for me".

If you're on 1.19.4, yes, config doesn't work with that one. Should work with 1.20 though.

**Comment by Pietr06** [comment]
doesnt work for me either (1.20.1)
![image](https://github.com/gbl/StepUp/assets/88508843/710fe403-dc5a-4291-822c-9b5e7accec9e)
[latest.log](https://github.com/gbl/StepUp/files/12145049/latest.log)

**Comment by gbl** [comment]
Just published version 1.3 which fixes this.

(If you had one of my other mods, like durabilityviewer or grid, installed, which came with a newer version of the config library, this got fixed automatically, so I guess not too many people had the problem).
