### ISSUE TITLE
Works in singleplayer but not on my server

### ISSUE THREAD

**Issue by katubug** [gbl/StepUp#4]
I run a server for my modpack and for some reason, StepUp isn't working on the server unless I use the vanilla autojump. In singleplayer, I have no issues with the whole-block step. As far as I know, nothing should be interfering?

Here's my server modlist:

> Folder PATH listing
> Volume serial number is 281A-ADB5
> C:.
> |   AdditionalAdditions-2.1.2.jar
> |   Adorn-2.1.4+1.17.1-fabric.jar
> |   advancements-enlarger-0.2.4.jar
> |   AmbientEnvironment-fabric-1.17.1-6.0.21.jar
> |   Angel-Ring-Fabric-1.17-1.0.1.jar
> |   appleskin-fabric-mc1.17-2.1.3.jar
> |   architectury-2.5.27-fabric.jar
> |   artifality-mc1.17.1-0.3.5.jar
> |   Artificial_Foliage_1.9_(FABRIC)_for_1.17-1.17.1.jar
> |   attachleadstologs-1.0.0-1.17.1.jar
> |   axolotl-item-fix-1.1.2.jar
> |   backpackmod-1.17-2.0.1.jar
> |   balancedrecall-1.0.0.jar
> |   balm-fabric-1.3.0+0.jar
> |   bclib-0.3.1.jar
> |   better-withered-mobs-1.6.1.jar
> |   blockus-2.2.8+1.17.1.jar
> |   BountifulFabric-1.0.0.jar
> |   can-i-mine-this-block-1.1.0.jar
> |   carrier-1.8.0.jar
> |   cavebiomes-0.6.3.jar
> |   chatplus-1.17.1-2.1.5.jar
> |   cloth-api-2.0.54.jar
> |   cloth-config-5.0.38-fabric.jar
> |   Clumps-fabric-1.17.1-7.0.5.jar
> |   comforts-fabric-0.0.6-1.17.1.jar
> |   companion-bats-fabric-1.17.6.jar
> |   cosmetic-armor-1.1.0.jar
> |   Couplings-1.5.1+1.17.jar
> |   Croptopia-1.17-FABRIC-1.6.1.jar
> |   culinaire-2.1.jar
> |   custom-stars-0.5.jar
> |   DarkPaintings-fabric-1.17.1-4.0.2.jar
> |   dawn-2.0.6.jar
> |   decorative-4.1.1.jar
> |   diggusmaximus-1.4.5-1.17.jar
> |   dontdropit-2.3.1+1.17.jar
> |   Earth2Java-1.7.3+1.17.jar
> |   eldritch-mobs-1.9.5.jar
> |   End Remastered 1.17.1 R4.1.0.jar
> |   endless_cake-1.0.0.jar
> |   enhancedcelestials-1.17.1-2.0.4.jar
> |   Erroring-Entity-Remover-1.0.1+1.17.1.jar
> |   extraalchemy-fabric-1.17.1-1.6.1.jar
> |   extra_enchants-0.1.2.jar
> |   fabric-api-0.40.0+1.17.jar
> |   fabric-language-kotlin-1.6.4+kotlin.1.5.30.jar
> |   FABRIC_1.17_chipped-1.1.1.jar
> |   FallingTree-1.17.1-2.13.0-2.jar
> |   ferritecore-3.0.3-fabric.jar
> |   Flonters-1.2.1+1.17.1.jar
> |   flytre-lib-1.3.7.jar
> |   geckolib-fabric-1.17-3.0.13.jar
> |   geodes-1.1.0.jar
> |   glassential-fabric-1.17-1.2.0.jar
> |   go-fish-1.3.0-beta-1.17.1.jar
> |   Gobber2-Fabric-1.17.1-2.4.44.jar
> |   grass-pass-1.17-1.0.0.jar
> |   gravelminer-fabric-11.0.0+0.jar
> |   grind-enchantments-1.3.0+1.17.1.jar
> |   GuardiansGalore-1.17.1-2.1.jar
> |   health-levels-1.0.1.jar
> |   HealthOverlay-1.17.1-4.0.2.jar
> |   hellish-materials-0.13.0.jar
> |   here-be-no-dragons-1.0.0.jar
> |   hookshot-r19.jar
> |   hydrogen-fabric-mc1.17.1-0.3.jar
> |   ImprovedHoes-Fabric-1.17.1-2.0.jar
> |   incantationem-1.1.2+1.17.1.jar
> |   indium-1.0.0+mc1.17.1.jar
> |   indypets-0.7.0.jar
> |   iris-mc1.17-1.1.1.jar
> |   Kambrik-1.1.0.jar
> |   keep-the-rain-0.2.0.jar
> |   Lakeside-1.1.0+1.17.jar
> |   lazydfu-0.1.2.jar
> |   lenientdeath-1.17.1-0.7.4.jar
> |   literally-chunk-loader-1.17.1-2.0.3.jar
> |   lithium-fabric-mc1.17.1-0.7.4.jar
> |   lovely_snails-1.0.3+1.17.jar
> |   mavm-1.0.5.jar
> |   mcda-1.7.10.jar
> |   mcdar-1.4.1.jar
> |   mcdw-3.4.1.jar
> |   mighty_mangoes-1.0.5.jar
> |   MobCatcher-Fabric-1.17.1-1.0.10.jar
> |   mods.txt
> |   morebakedfoods-1.2.0.jar
> |   moreberries-1.4.2.jar
> |   MoreGems-Fabric-1.17.1-1.2.34.jar
> |   morevillagers-FABRIC-1.17-2.1.0.jar
> |   mostructures-1.3.0-pre1-1.17.1-fabric.jar
> |   mythic-mounts-1.17.1-1.2.jar
> |   nauticality-0.1.2.jar
> |   netherite-nuggets-1.3.0.jar
> |   notenoughcrashes-3.4.4+1.17-fabric.jar
> |   outvoted-2.0.0-alpha.12-fabric.jar
> |   oxidized-1.3.0.jar
> |   Patchouli-1.17-54-FABRIC.jar
> |   Paxi-Fabric-1.17-1.2.2.jar
> |   pettable-1.2.0.jar
> |   Platypuses 1.0.0-FABRIC_1.17.jar
> |   polymorph-fabric-0.0.12-1.17.1.jar
> |   ppp-1.17.1-1.3.0.jar
> |   promenade-2.1.2.jar
> |   RandomTP-5.0.1+1.17-fabric.jar
> |   reapingmod-1.4.0.jar
> |   repurposed_structures_fabric-2.3.3+1.17.1.jar
> |   reroll-1.3.0-1.17.1.jar
> |   ResourcefulTools-Fabric-1.17.1-1.1.20.jar
> |   rocks-1.4.0.jar
> |   RoughlyEnoughItems-6.0.279-alpha-fabric.jar
> |   ruined-equipment-1.3.0.jar
> |   sentimentality3-1.3.2.jar
> |   simplegrinder-17.0.1-Fabric.jar
> |   simpletech-0.0.5.jar
> |   skylorlib-1.0.3.jar
> |   someforgepatchesported-1.0.1.jar
> |   spirit-1.1.0.jar
> |   suitablystackablestew-1.1.2.jar
> |   The_Graveyard_1.2_(FABRIC)_for_1.17-1.17.1.jar
> |   the_loved_ones-1.2.0+1.17.jar
> |   things-0.2.5.jar
> |   tokenablefurnaces-1.1.2.jar
> |   tomsstorage-1.1.14.jar
> |   traverse-4.0.0-beta.2.jar
> |   trinkets-3.0.4.jar
> |   untitledduckmod-0.3.0-fabric.jar
> |   VanillaTweaks-1.17.1-1.0.11.jar
> |   vanilla_degus-1.17.1-v1.2.0-fabric.jar
> |   wanderingcollector-1.0.2+mc1.17.jar
> |   whereisit-1.17.1-1.13.5.jar
> |   winged-1.17.1-3.0.0.jar
> |   wthit-fabric-3.8.1.jar
> |   xpstorage_trinkets-0.1+1.17.1.jar
> |   xp_storage-1.4.2+1.17.1.jar
> |   yatm-0.1.1.jar
> |   YungsApi-1.17-Fabric-16.jar
> |   [server] Chunky-1.2.124.jar
> |   [server] essential_commands-0.16.1-mc1.17.jar
> |   [server] Fabric-Discord-Link-0.9.6.jar
> |   [server] kits-1.3.0-mc1.17.jar
> |   [server] LuckPerms-Fabric-5.3.64.jar
> |   [server] player-roles-1.4.3.jar
> |   [server] spark-fabric.jar
> |   [server] textile_backup-2.2.0-1.17.jar
> |   
> +---literally_chunk_loader
> |   \---world
> |           chunks.data
> |           
> \---luckperms
>     |   contexts.json
>     |   luckperms-h2.mv.db
>     |   
>     \---libs
>             adventure-4.8.1-remapped.jar
>             adventure-4.8.1.jar
>             asm-9.1.jar
>             asm-commons-9.1.jar
>             bytebuddy-1.10.22-remapped.jar
>             bytebuddy-1.10.22.jar
>             caffeine-2.9.0-remapped.jar
>             caffeine-2.9.0.jar
>             configurate-core-3.7.2-remapped.jar
>             configurate-core-3.7.2.jar
>             configurate-hocon-3.7.2-remapped.jar
>             configurate-hocon-3.7.2.jar
>             event-3.0.0-remapped.jar
>             event-3.0.0.jar
>             h2-driver-1.4.199.jar
>             hocon-config-1.4.1-remapped.jar
>             hocon-config-1.4.1.jar
>             jar-relocator-1.4.jar
>             okhttp-3.14.9-remapped.jar
>             okhttp-3.14.9.jar
>             okio-1.17.5-remapped.jar
>             okio-1.17.5.jar

**Comment by gbl** [comment]
Some servers detect and prevent stepping up. Sorry, I won't go through the mod list and check what each of them does, but if any of them has a "cheat prevention" feature, that'll probably be it. 

(I even got banned from a server once for cheating, approx. 10 seconds after joining it, when I had stepup active)
