### ISSUE TITLE
Consider an 'opt-in' keybind

### ISSUE THREAD

**Issue by Qendolin** [gbl/StepUp#5]
I suggest removing the keybind by default.
I see this with a lot of mods that add a feature and assign a default keybind but often it is not really useful and presents issues when running the game with many mods.
I think the same applies here:
1. Changing the step mode while ingame is not a common occurrence
2. It's more annoying to remove a keybind than to add one

That's of course just my opinion but I think an 'opt-in' keybind is much more sensible for small mods.

**Comment by gbl** [comment]
I disagree with "it's more annoying ..." - if there is no bound key by default, people will ask how to use the mod and complain it's doing nothing. Especially if it's the first time they're using mods. People with many mods for who this might be a problem are more easily able to help themselves.
