### ISSUE TITLE
Are we able to remove vanilla autojump via config?

### ISSUE THREAD

**Issue by DemonSlayer112** [gbl/StepUp#9]
Hi, love the mod, but are we able to remove vanilla auto jump?
I want this mod off by default, and toggle from off to on.
But idk how to set this via config? I tried changing it, but any change i do rewrites itself :(

**Comment by gbl** [comment]
The mod always cycles between all 3 modes. The config just sets what's the initial value when joining a world/server.

**Comment by DemonSlayer112** [comment]
I tried changing things in the config but no matter what i changed the config changes it all to default, so editing the config just doesn't work.
